"""add feature flags

Revision ID: 474c99aec5bd
Revises: 24bb2e4a195c
Create Date: 2022-08-04 17:33:06.793159

"""


# revision identifiers, used by Alembic.
revision = "474c99aec5bd"
down_revision = "24bb2e4a195c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
